import = ["~/.config/alacritty/solarized.toml"]

[shell]
program = "zsh"
args = ["-l", "-c", "tmux && exec zsh"]

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "]", mods = "Command", chars = "\u001d" },
  { key = "1", mods = "Command", chars = "\u0001\u0031" },
  { key = "2", mods = "Command", chars = "\u0001\u0032" },
  { key = "3", mods = "Command", chars = "\u0001\u0033" },
  { key = "4", mods = "Command", chars = "\u0001\u0034" },
  { key = "5", mods = "Command", chars = "\u0001\u0035" },
  { key = "6", mods = "Command", chars = "\u0001\u0036" },
  { key = "A", mods = "Command", chars = "\u0001" },
  { key = "B", mods = "Command", chars = "\u0002" },
  { key = "C", mods = "Command", chars = "\u0003" },
  { key = "D", mods = "Command", chars = "\u0004" },
  { key = "E", mods = "Command", chars = "\u0005" },
  { key = "F", mods = "Command", chars = "\u0006" },
  { key = "G", mods = "Command", chars = "\u0007" },
  { key = "K", mods = "Command", chars = "\u000b" },
  { key = "L", mods = "Command", chars = "\u000c" },
  { key = "N", mods = "Command", chars = "\u000e" },
  { key = "O", mods = "Command", chars = "\u000f" },
  { key = "P", mods = "Command", chars = "\u0010" },
  { key = "R", mods = "Command", chars = "\u0012" },
  { key = "S", mods = "Command", chars = "\u0013" },
  { key = "T", mods = "Command", chars = "\u0014" },
  { key = "U", mods = "Command", chars = "\u0015" },
  { key = "Z", mods = "Command", chars = "\u001a" },
]
