[user]
name = "Karol Moroz"
email = "karol@moroz.dev"

[signing]
behavior = "drop"
backend = "gpg"
key = "9643ACD937ED3E82E9E25B8FBA266278CB48B02B"

[git]
sign-on-push = true

[aliases]
up = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail

jj git fetch
jj rebase --skip-emptied -d 'trunk()'
"""]

tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[revsets]
trunk = "main@origin | master@origin"
