# load with dconf load /org/cinnamon/desktop/keybindings/ < keybindings.conf

[media-keys]
area-screenshot=['<Shift>Print', '<Primary><Shift>dollar']
area-screenshot-clip=['<Control><Shift>Print', '<Primary><Shift><Super>dollar']
screensaver=['<Primary><Super>apostrophe', 'XF86ScreenSaver']
screenshot=['Print', '<Primary><Shift>numbersign']
screenshot-clip=['<Control>Print', '<Primary><Shift><Super>numbersign']
window-screenshot=['<Alt>Print', '<Primary><Shift>percent']
window-screenshot-clip=['<Control><Alt>Print', '<Primary><Shift><Super>percent']

[wm]
close=['<Alt>F4', '<Primary>q']
maximize=['<Primary><Alt><Super>m']
